### ISSUE TITLE
Not able to access the Juypter notebook from Host

### ISSUE THREAD

**Issue by siddhantGupta123** [gw0/docker-keras#2]
Hello,
I am not able to access the Juypter note book from host, I am trying "localhost:8888", getting below error on container dos prompt:
**No web browser found: could not locate runnable browser.**

**Comment by gw0** [comment]
The image **gw000/keras** is supposed to be a more or less minimalistic image for Docker image with Keras. If you want IPython, Jupyter, and many other data analysis tools, you either:

- extended it to your needs by writing your `Dockerfile`
- use the [**gw000/keras-full** image](https://github.com/gw0/docker-keras-full) that is supposed to be a full-blown Jupyter environment with Keras

Containers with **gw000/keras-full** work as expected (open browser on http://127.0.0.1:8888/):

```
$ sudo docker run -it --rm -p=6006:6006 -p=8888:8888 gw000/keras-full
[I 12:38:04.364 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 12:38:04.384 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 12:38:04.394 NotebookApp] Serving notebooks from local directory: /srv
[I 12:38:04.394 NotebookApp] 0 active kernels 
[I 12:38:04.394 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 12:38:04.394 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
