### ISSUE TITLE
There is no PIL library

### ISSUE THREAD

**Issue by zhangzhishan** [gw0/docker-keras#3]

**Comment by gw0** [comment]
Image **gw000/keras** is supposed to be a more or less minimalistic Docker image with Keras. It is supposed that you extended it to your needs by writing your `Dockerfile`. For PIL it would probably be the easiest to install it system-wide with the corresponding Debian package `python-pil` (or `python-pillow` that is a drop-in replacement), eg:

```
FROM gw000/keras:1.2.0-py2

# install your app dependencies
RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y python-pil

# install your app
ADD ai/ /srv/ai/
RUN chmod +x /srv/ai/run.py

CMD ["/srv/ai/run.py"]
```

**Comment by gw0** [comment]
I have improved the [example in documentation](https://github.com/gw0/docker-keras) based on this.
